2020-10-11 18:18:42 - Y:/python_API_AutoTest_include_excel/common/run_all.py[line:33] - INFO: ********************自动化测试开始********************
2020-10-11 18:18:44 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：get_category
2020-10-11 18:18:45 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:173] - INFO: 断言通过
2020-10-11 18:18:45 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：query_goods_list_1
2020-10-11 18:18:46 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:173] - INFO: 断言通过
2020-10-11 18:18:46 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：query_goods_list_2
2020-10-11 18:18:46 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:241] - INFO: 断言通过
2020-10-11 18:18:46 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：query_event_get_1
2020-10-11 18:18:47 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:173] - INFO: 断言通过
2020-10-11 18:18:47 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：query_event_post_1
2020-10-11 18:18:47 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:248] - INFO: 断言通过
2020-10-11 18:18:47 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：query_event_post_2
2020-10-11 18:18:47 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:113] - INFO: 断言通过
2020-10-11 18:18:47 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：event_name_reasonable_1
2020-10-11 18:18:48 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:193] - INFO: 断言通过
2020-10-11 18:18:48 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：event_name_no_exist_1
2020-10-11 18:18:48 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:193] - INFO: 断言通过
2020-10-11 18:18:48 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：event_name_null_1
2020-10-11 18:18:48 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:193] - INFO: 断言通过
2020-10-11 18:18:48 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：event_name_other_character_1
2020-10-11 18:18:49 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:193] - INFO: 断言通过
2020-10-11 18:18:49 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：event_name_reasonable_2
2020-10-11 18:18:49 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:248] - INFO: 断言通过
2020-10-11 18:18:49 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：event_name_no_exist_2
2020-10-11 18:18:49 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:248] - INFO: 断言通过
2020-10-11 18:18:49 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：event_name_null_2
2020-10-11 18:18:49 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:248] - INFO: 断言通过
2020-10-11 18:18:50 - Y:\python_API_AutoTest_include_excel\common\handle_excel_test_cases.py[line:94] - INFO: 当前用例为：event_name_other_character_2
2020-10-11 18:18:50 - Y:\python_API_AutoTest_include_excel\common\ferry_API_auto_test_key_function.py[line:248] - INFO: 断言通过
2020-10-11 18:18:50 - Y:/python_API_AutoTest_include_excel/common/run_all.py[line:53] - INFO: *********************自动化测试结束*********************
2020-10-11 18:18:51 - Y:\python_API_AutoTest_include_excel\common\ferry_email_manager.py[line:55] - INFO: 邮件已发送成功
